# Generated by Django 5.1.10 on 2026-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(blank=True, default='Guest', max_length=50, null=True),
        ),
    ]
